### ISSUE TITLE
Lamda error while executing the code

### ISSUE THREAD

**Issue by Dhanalakshmi07** [trinhbiendich/extract-image-from-video#1]
When I excute the code, Iam getting this error:'
 File "setup.py", line 31
    return reduce(lambda x, (y, z): x | (z << y),
                            ^
SyntaxError: invalid syntax

Please help me to write the above expression in python 3

**Comment by trinhbiendich** [comment]
Hi @Dhanalakshmi07 

I fixed, pls help me recheck
This issues got by in python 3, Print must use with parentheses, It's not issues by lambda

Regards,
Sac

**Comment by Dhanalakshmi07** [comment]
Dear Sir,
After including parenthesis in python 3,  it is showing the same error in
lambda expression, when I surfed through site,  I came to know that it is
unable to execute three variable in lambda expression in python 3. I have
tried in both python 2 and python 3 . These are my outputs:
*while executing in Python 2, following is the error:*
(cv) (base) dhana@localhost:~/Desktop/Dataset/11.12.19/extract-image-from-video-master$
python2 setup.py -p /home/dhana/Desktop/Dataset/11.12.19/extract-ima
ge-from-video-master/sample_videos/sample.mp4 -f 0 -e True -t 60 -rd True
-max 95 -s
/home/dhana/Desktop/Dataset/11.12.19/extract-image-from-video-master/output/
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    totalFrames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
AttributeError: 'module' object has no attribute 'CAP_PROP_FRAME_COUNT'

*while executing in Python 3, following is the error:*
(cv) (base) dhana@localhost:~/Desktop/Dataset/11.12.19/extract-image-from-video-master$
python setup3.py -p
/home/dhana/Desktop/Dataset/11.12.19/extract-image-from-video-master/sample_videos/sample.mp4
-f 0 -e True -t 60 -rd True -max 95 -s
/home/dhana/Desktop/Dataset/11.12.19/extract-image-from-video-master/output/
totalFrames=  900
timeLength=  299 s
fps=  29.97002997002997 /s
======================================
path:
/home/dhana/Desktop/Dataset/11.12.19/extract-image-from-video-master/sample_videos/sample.mp4
Save to:
/home/dhana/Desktop/Dataset/11.12.19/extract-image-from-video-master/output/
Frame started: 0
Enable extract: True
Enable debug: False
Threshold: 60.0
Percent the same: 95 %
Remove duplicate: True
======================================
Traceback (most recent call last):
  File "setup3.py", line 132, in <module>
    hash1 = avhash(pil_im)
  File "setup3.py", line 33, in avhash
    0)
TypeError: <lambda>() missing 1 required positional argument: 'z'



Kindly help me out. Thanks in advance.
